### ISSUE TITLE
Changing reading list from text to markdown

### ISSUE THREAD

**Issue by adib2149** [shionguha/cosc4931-socialethicalimp-fa18#23]
Hi,

This is probably not very important, but can we have the [reading list text file](https://github.com/shionguha/cosc4931-socialethicalimp-fa18/blob/master/Readings.txt) as a markdown file? It is simpler to go through a markdown than a text file. 

I can make the changes too, if that's okay. Thank you.

**Comment by shionguha** [comment]
@adib2149 can you make the changes and send a pull request?

**Comment by adib2149** [comment]
Hello Dr. Guha, I've made a pull request. Thank you.

**Comment by shionguha** [comment]
thanks a lot. I really appreciate it.
